package org.team340.lib.swerve.config;

import com.ctre.phoenix6.hardware.TalonFX;
import java.util.MissingResourceException;
import org.team340.lib.swerve.hardware.SwerveIMUs;
import org.team340.lib.swerve.hardware.SwerveIMUs.SwerveIMU;

/**
 * Config builder for {@link SwerveBase}.
 */
public class SwerveConfig {

    /** The robot's main loop period in seconds. */
    public double period = -1.0;
    /** The period to update odometry in seconds. */
    public double odometryPeriod = -1.0;
    /** The period to look ahead for discretizing chassis speeds in seconds. */
    public double discretizationPeriod = -1.0;
    /** PID gains for move motors, as a tuple of {@code [kP, kI, kD, iZone]}. */
    public double[] movePID;
    /** Feed forward gains for move motors, as a tuple of {@code [kS, kV]}. */
    public double[] moveFF;
    /** PID gains for turn motors, as a tuple of {@code [kP, kI, kD, iZone]}. */
    public double[] turnPID;
    /** If the move motors should have brake mode enabled. */
    public boolean moveBrakeMode = false;
    /** If the turn motors should have brake mode enabled. */
    public boolean turnBrakeMode = false;
    /** The maximum forward velocity the robot is capable of in meters/second. */
    public double velocity = -1.0;
    /** The maximum acceleration the robot is capable of in meters/second/second. */
    public double accel = -1.0;
    /** The maximum angular acceleration the robot is capable of in radians/second/second. */
    public double angularAccel = -1.0;
    /** The maximum velocity for driver input in meters/second. */
    public double driverVel = -1.0;
    /** Exponential power to apply to driver velocity. */
    public double driverVelExp = -1.0;
    /** The maximum angular velocity for driver input in radians/second. */
    public double driverAngularVel = -1.0;
    /** Exponential power to apply to driver angular velocity. */
    public double driverAngularVelExp = -1.0;
    /** The robot's nominal voltage. Typically {@code 12.0}. */
    public double voltage = -1.0;
    /** The current limit in amps for move motors. */
    public double moveCurrentLimit = -1.0;
    /** The current limit in amps for turn motors. */
    public double turnCurrentLimit = -1.0;
    /** The move gear ratio, in motor rotations/wheel rotation. */
    public double moveGearRatio = -1.0;
    /** The turn gear ratio, in motor rotations/module rotation. */
    public double turnGearRatio = -1.0;
    /** The ratio between the wheel and the module's angle. */
    public double couplingRatio = -1.0;
    /** The wheel diameter in meters. */
    public double wheelDiameter = -1.0;
    /** Standard deviations for odometry, as a tuple of {@code [x, y, angular]}. */
    public double[] odometryStd;
    /** The IMU to use, generated by the {@link SwerveIMUs} class. */
    public SwerveIMU.Ctor imu;
    /** Name of the CAN bus utilized by Phoenix devices. */
    public String phoenixCanBus = "";
    /** {@code true} if Phoenix Pro is active on <i>all</i> devices used by the swerve API. */
    public boolean phoenixPro = false;
    /** If move motors should enable FOC. */
    public boolean phoenixMoveFOC = false;
    /** If turn motors should enable FOC. */
    public boolean phoenixTurnFOC = false;
    /** Configurations for swerve modules. */
    public SwerveModuleConfig[] modules;

    /**
     * Sets various timings utilized by the robot.
     * @param period The robot's main loop period in seconds.
     * @param odometry The period to update odometry in seconds.
     * @param discretization The period to look ahead for discretizing chassis speeds in seconds.
     */
    public SwerveConfig setTimings(double period, double odometry, double discretization) {
        this.period = period;
        odometryPeriod = odometry;
        discretizationPeriod = discretization;
        return this;
    }

    /**
     * Sets PID gains for move motors. Note that {@link TalonFX} motors do not support {@code iZone}.
     * @param kP Proportional gain constant.
     * @param kI Integral gain constant.
     * @param kD Derivative gain constant.
     * @param iZone Integral range.
     */
    public SwerveConfig setMovePID(double kP, double kI, double kD, double iZone) {
        movePID = new double[] { kP, kI, kD, iZone };
        return this;
    }

    /**
     * Sets feed forward constants for move motors. A good starting point is a {@code kV}
     * value of {@code <Optimal Voltage> / <Max Velocity>}. These values can be obtained
     * via characterization using sysID with a real robot.
     * @param kS The static gain.
     * @param kV The velocity gain.
     */
    public SwerveConfig setMoveFF(double kS, double kV) {
        moveFF = new double[] { kS, kV };
        return this;
    }

    /**
     * Sets PID gains for turn motors. Note that {@link TalonFX} motors do not support {@code iZone}.
     * @param kP Proportional gain constant.
     * @param kI Integral gain constant.
     * @param kD Derivative gain constant.
     * @param iZone Integral range.
     */
    public SwerveConfig setTurnPID(double kP, double kI, double kD, double iZone) {
        this.turnPID = new double[] { kP, kI, kD, iZone };
        return this;
    }

    /**
     * Sets motor brake modes.
     * @param move If the move motors should have brake mode enabled.
     * @param turn If the turn motors should have brake mode enabled.
     */
    public SwerveConfig setBrakeMode(boolean move, boolean turn) {
        moveBrakeMode = move;
        turnBrakeMode = turn;
        return this;
    }

    /**
     * Sets limits for the drivetrain.
     *
     * <br><br>
     * You may find more predictable behavior by setting these values slightly lower than the actual maximum capabilities of your robot.
     * It is recommended that these values are found empirically using an actual robot. An easy way to do so is to configure infeasible limits, then analyze telemetry.
     *
     * @param velocity The maximum forward velocity the robot is capable of in meters/second. More specifically, the maximum velocity a move motor is capable of.
     * @param accel The maximum acceleration the robot is capable of in meters/second/second.
     * @param angularAccel The maximum angular acceleration the robot is capable of in radians/second/second.
     */
    public SwerveConfig setLimits(double velocity, double accel, double angularAccel) {
        this.velocity = velocity;
        this.accel = accel;
        this.angularAccel = angularAccel;
        return this;
    }

    /**
     * Configures the profile to apply to speeds calculated using the driver's controller input.
     * @param velocity The maximum velocity for driver input in meters/second.
     * @param velocityExp Exponential power to apply to driver velocity. {@code 1.0} effectively disables.
     * @param angularVel The maximum angular velocity for driver input in radians/second.
     * @param angularVelExp Exponential power to apply to driver angular velocity. {@code 1.0} effectively disables.
     */
    public SwerveConfig setDriverProfile(double velocity, double velocityExp, double angularVel, double angularVelExp) {
        driverVel = velocity;
        driverVelExp = velocityExp;
        driverAngularVel = angularVel;
        driverAngularVelExp = angularVelExp;
        return this;
    }

    /**
     * Sets power properties.
     * @param voltage The robot's nominal voltage. Typically {@code 12.0}.
     * @param moveCurrentLimit The current limit in amps for move motors.
     * @param turnCurrentLimit The current limit in amps for turn motors.
     */
    public SwerveConfig setPowerProperties(double voltage, double moveCurrentLimit, double turnCurrentLimit) {
        this.voltage = voltage;
        this.moveCurrentLimit = moveCurrentLimit;
        this.turnCurrentLimit = turnCurrentLimit;
        return this;
    }

    /**
     * Sets swerve gearing properties.
     * @param moveRatio The move gear ratio, in motor rotations/wheel rotation.
     * @param turnRatio The turn gear ratio, in motor rotations/module rotation.
     * @param couplingRatio The ratio between the wheel and the module's angle. Used as a compensation factor for odometry, set to {@code 0.0} to disable.
     * @param wheelDiameter The wheel diameter in meters.
     */
    public SwerveConfig setMechanicalProperties(double moveRatio, double turnRatio, double couplingRatio, double wheelDiameter) {
        moveGearRatio = moveRatio;
        turnGearRatio = turnRatio;
        this.couplingRatio = couplingRatio;
        this.wheelDiameter = wheelDiameter;
        return this;
    }

    /**
     * Sets the standard deviations for pose estimation from module odometry.
     * A good starting configuration is all axis with a magnitude of {@code 0.1}.
     * @param x The X axis standard deviation in meters.
     * @param y The Y axis standard deviation in meters.
     * @param angular The angular standard deviation in radians.
     */
    public SwerveConfig setOdometryStd(double x, double y, double angular) {
        this.odometryStd = new double[] { x, y, angular };
        return this;
    }

    /**
     * Sets the IMU to use.
     * @param imu The IMU to use, generated by the {@link SwerveIMUs} class.
     */
    public SwerveConfig setIMU(SwerveIMU.Ctor imu) {
        this.imu = imu;
        return this;
    }

    /**
     * Sets available features for Phoenix devices. For Phoenix Pro features to be utilized by the Swerve API,
     * all devices must be activated, and intrinsically must all be Phoenix devices (Pigeon2 + TalonFX + CANcoder).
     * This configuration option can be omitted safely if its features are not needed.
     * @param canBus Name of the CAN bus utilized by Phoenix devices.
     * @param pro {@code true} if Phoenix Pro is active on <i>all</i> devices used by the swerve API.
     * @param moveFOC If move motors should enable FOC. {@code pro} can still be {@code false} while enabling FOC, provided all move motors are still licensed.
     * @param turnFOC If turn motors should enable FOC. {@code pro} can still be {@code false} while enabling FOC, provided all turn motors are still licensed.
     */
    public SwerveConfig setPhoenixFeatures(String canBus, boolean pro, boolean moveFOC, boolean turnFOC) {
        phoenixCanBus = canBus;
        phoenixPro = pro;
        phoenixMoveFOC = moveFOC;
        phoenixTurnFOC = turnFOC;
        return this;
    }

    /**
     * Sets module configs.
     * See {@link SwerveModuleConfig}.
     * @param modules The configs of the swerve modules.
     */
    public SwerveConfig setModules(SwerveModuleConfig... modules) {
        this.modules = modules;
        return this;
    }

    /**
     * Verifies the config as well as the config's modules.
     * Throws an error if an issue is found.
     */
    public void verify() {
        if (period == -1.0) throwMissing("Period");
        if (odometryPeriod == -1.0) throwMissing("Odometry Period");
        if (discretizationPeriod == -1.0) throwMissing("Discretization Period");
        if (movePID == null) throwMissing("Move PID");
        if (moveFF == null) throwMissing("Move FF");
        if (turnPID == null) throwMissing("Turn PID");
        if (velocity == -1.0) throwMissing("Velocity");
        if (accel == -1.0) throwMissing("Acceleration");
        if (angularAccel == -1.0) throwMissing("Angular Acceleration");
        if (driverVel == -1.0) throwMissing("Driver Velocity");
        if (driverVelExp == -1.0) throwMissing("Driver Velocity Exponential");
        if (driverAngularVel == -1.0) throwMissing("Driver Angular Velocity");
        if (driverAngularVelExp == -1.0) throwMissing("Driver Angular Velocity Exponential");
        if (voltage == -1.0) throwMissing("Voltage");
        if (moveCurrentLimit == -1.0) throwMissing("Move Current Limit");
        if (turnCurrentLimit == -1.0) throwMissing("Turn Current Limit");
        if (moveGearRatio == -1.0) throwMissing("Move Gear Ratio");
        if (turnGearRatio == -1.0) throwMissing("Turn Gear Ratio");
        if (couplingRatio == -1.0) throwMissing("Coupling Ratio");
        if (wheelDiameter == -1.0) throwMissing("Wheel Diameter");
        if (odometryStd == null) throwMissing("Odometry Standard Deviations");
        if (imu == null) throwMissing("IMU");
        if (modules == null) throwMissing("Modules");

        for (SwerveModuleConfig module : modules) {
            module.verify();
        }
    }

    private void throwMissing(String key) {
        throw new MissingResourceException("Missing value: " + key, this.getClass().getSimpleName(), key);
    }
}
