name: Robot Code
on: [pull_request, push]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    container: wpilib/ubuntu-base:22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check robot code formatting
        run: ./gradlew spotlessCheck

  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Ensure spotless will not fail on build
        run: ./gradlew spotlessApply

      - name: Compile and run tests on robot code
        run: ./gradlew build
